apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xeric-baboon-java-quarkus
  janus-idp.io/tekton: xeric-baboon-java-quarkus
  backstage.io/kubernetes-id: xeric-baboon-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-e2e-demo 
  app.kubernetes.io/part-of: xeric-baboon-java-quarkus
resources: 
- deployment.yaml
- route.yaml
- service.yaml
